// Generated by https://quicktype.io

export interface TeamData {
  id:                        string;
  team:                      string;
  ncaa_name:                 string;
  espn_name:                 string;
  link:                      string;
  espn_url:                  string;
  espn_team_full_url:        string;
  espn_stats_url:            string;
  espn_games_url:            string;
  espn_abbrv:                string;
  espn_pbp:                  string;
  conference:                string; 
  primary_color:             string;
  secondary_color:           string;
}


export enum Region {
  E = "E",
  Empty = "-",
  M = "M",
  S = "S",
  W = "W",
}

// Generated by https://quicktype.io

export interface Player {
  playerId: string;
  teamId: string;
  player:                        string;
  position:                      Position | string;
  gamesPlayed:                   string;
  gamesStarted:                  string;
  minutesPerGame:                number;
  pointsPerGame:                 number;
  fieldGoalsMade:                string;
  fieldGoalsAttempted:           string;
  fieldGoalPercentage:           string;
  threePointFieldGoalsMade:      string;
  threePointFieldGoalsAttempted: string;
  threePointFieldGoalPercentage: string;
  playerLink:                    string;
  playerGameLogLink:             string;
  gamesProjection:              number;
  pointsProjection:             number;
  assists: number;
  assists_per_game: number;
  turnovers: number;
  turnovers_per_game: number;
  assists_per_turnover: number;
}

export enum Position {
  C = "C",
  F = "F",
  G = "G",
}

export interface PlayerGameStats {
  game_date: string | Date | null;
  player_id: string | null;
  team_id: string | null;
  minutes_played: number;
  points: number;
  game_id: string;
  is_post_season: boolean | string;
  game_result: string | null;
}


